baseurl = "http://sgonzalez.tech/"
canonifyurls = false
defaultcontentlanguage = "en"
disqusShortname = "sgonzalez"
languagecode = "en"
paginate = 20
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "b2"
theme = "hugo-coder"
title = "Santiago GonzÃ¡lez Tech"

[languages.en]
  languagename = "English"
  contentDir = "content/en"
  [[languages.en.menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[languages.en.menu.main]]
    name = "About"
    url = "about/"
    weight = 2
  [[languages.en.menu.main]]
    name = "Portfolio"
    url = "portfolio/"
    weight = 3
  [[languages.en.menu.main]]
    name = "Contact"
    url = "contact/"
    weight = 4
[languages.es]
  languagename = "EspaÃ±ol"
  title = "Santiago GonzÃ¡lez"
  contentDir = "content/es"
  [[languages.es.menu.main]]
    name = "Inicio"
    url = ""
    weight = 1
  [[languages.es.menu.main]]
    name = "Acerca MÃ­"
    url = "about/"
    weight = 2
  [[languages.es.menu.main]]
    name = "Portafolio"
    url = "portfolio/"
    weight = 3
  [[languages.es.menu.main]]
    name = "Contacto"
    url = "contact/"
    weight = 4
  [languages.es.params]
    author = "Santiago GonzÃ¡lez"
    description = "PÃ¡ginas Web, Juegos, Aplicaciones Desktop, Apps MÃ³viles, Web, Â¡y mucho mÃ¡s! Ponte en contacto si tienes interÃ©s en lograr algo juntos. Desarrollador de Software y Aficionado al desarrollo VG, un pequeÃ±o genio. ðŸ¤“"
    footercontent = "Gracias por visitar mi pÃ¡gina ðŸ˜Š"
    info = "DevOps & Software"
    keywords = "blog,desarrollador,personal,devops,software"
    since = 2020

[params]
  author = "Santiago GonzÃ¡lez"
  avatarurl = "images/avatar.jpg"
  previewurl = "https://sgonzalez.tech/images/preview.png"
  colorscheme = "auto"
  commit = "https://github.com/netrules/sgonzalez-tech/tree/"
  custom_css = []
  custom_js = ["js/custom.js"]
  dateformat = "January 2006"
  description = "Websites, Games, Desktop Applications, Mobile Apps, Web & Much More! Feel free to chat me up if you're interested in doing some work together. Software Developer & Game Enthusiast, all around geek! ðŸ¤“"
  footercontent = "Thanks for viewing my website ðŸ˜Š"
  hideCopyright = false
  hideCredits = false
  info = "DevOps & Software"
  keywords = "blog,developer,personal,devops,software"
  maxSeeAlsoItems = 5
  rtl = false
  since = 2020
  [params.ads]
    enabled_embed = ["bluehost","unity","livechat","adsterra", "greengeeks", "shareasale", "shortest"]
  [params.ads.embed]
    bluehost = [
      "<a href='https://www.bluehost.com/track/sgonzalez/' target='_blank'> <img border='0' src='/please-dont-block-me/bluehost-728x90BW.png'> </a>"
    ]
    livechat = [
      "<a href='https://www.livechat.com/?a=H2idxmLMg&utm_source=PP&utm_campaign=default_link&utm_source=PP&utm_medium=banner&utm_content=v56'><img src='https://cdn.livechatinc.com/partners/production/img/resources/livechat_v56@2x.jpg' alt='Live Chat Software' /></a>"
    ]
    unity = [
      "<iframe src='https://assetstore.unity.com/linkmaker/embed/list/6/widget-wide-light?aid=1100lfT2L' style='width:100%; height:100px; border:0px; display: block; margin: auto;'></iframe>"
    ]
    greengeeks = [
      "<a href='https://www.greengeeks.com/track/santythedev/cp-default' target='_top'><img border='0' src='/please-dont-block-me/greengeeks-728x90BW.png'></a>"
    ]
    shareasale = [
      "<a target='_blank' href='https://shareasale.com/r.cfm?b=922009&amp;u=2708801&amp;m=47&amp;urllink=&amp;afftrack='><img src='/please-dont-block-me/ShareASale-728x90BW.png' border='0' /></a>"
    ]
    shortest = [
      "<a href='http://join-shortest.com/ref/e7ca0624b7?user-type=new'><img src='/please-dont-block-me/shortest-728x90BW.png' title='Los enlaces mÃ¡s pequeÃ±os, el pago mÃ¡s grande' width='728' height='90' />#ref-menu</a>"
    ]
  [params.affiliate]
    infolinks = false
  [params.fathomAnalytics]
    serverURL = "analytics.sgonzalez.tech"
    siteID = "ABCDE"
  [[params.social]]
    icon = "fab fa-github"
    name = "Github"
    url = "https://github.com/netrules/"
    weight = 1
  [[params.social]]
    icon = "fab fa-medium"
    name = "Medium"
    url = "https://medium.com/@santythedev"
    weight = 2
  [[params.social]]
    icon = "fas fa-rss"
    name = "RSS"
    rel = "alternate"
    type = "application/rss+xml"
    url = "https://sgonzalez.tech/index.xml"
    weight = 3

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
